sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - apache2-utils
    - shellcheck

before_script:
  - ./bin/build-dev
  - ./bin/start

script:
  - ./bin/test
  # Stopping the services isn't part of the test, but we need it to break the build if it fails.
  - ./bin/stop
