sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
      - apache2-utils
      - shellcheck
  hosts:
    # Used by ./tests/web-service-proxy-test.
    - consul.maison

before_script:
  - ./bin/build-dev

  # Set up maison-services.
  - git clone https://github.com/bartfeenstra/maison-services.git ./vendor/maison-services
  - ./vendor/maison-services/bin/build
  - ./vendor/maison-services/bin/start
  - ./vendor/maison-services/bin/await

  # Update configuration with actual maison-services values.
  - . ./vendor/maison-services/run/.env
  - sed -Ei "s/^MAISON_DMX_CONSUL_ADDRESS=.*$/MAISON_DMX_CONSUL_ADDRESS=$MAISON_SERVICES_ADVERTISE_IP/" ./.env
  - sed -Ei "s/^MAISON_DMX_CONSUL_TOKEN=.*$/MAISON_DMX_CONSUL_TOKEN=$MAISON_SERVICES_CONSUL_SERVICE_ACL_TOKEN/" ./.env

  - ./bin/start

script:
  - ./bin/test
  # Stopping the services isn't part of the test, but we need it to break the build if it fails.
  - ./bin/stop
