version: '3.4'
services:
  web:
    image: maison:web
    build: ./services/web
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - './data/services/web/htpasswd:/etc/nginx/htpasswd'
      - './data/services/web/letsencrypt:/etc/letsencrypt'
    expose:
     - '80'
     - '443'
    ports:
     - '80:80'
     - '443:443'
    environment:
      MAISON_WEB_PROTOCOL: '${MAISON_WEB_PROTOCOL}'
      MAISON_WEB_DOMAIN: '${MAISON_WEB_DOMAIN}'
      MAISON_WEB_CONSUL_IP: '$$MAISON_WEB_CONSUL_IP}'
      MAISON_WEB_CONSUL_TOKEN: '${MAISON_WEB_CONSUL_TOKEN}'
